### ISSUE TITLE
Sky flashing

### ISSUE THREAD

**Issue by Twinkletoe** [ChildrenOfUr/coUclient#101]
I am in Chrome. When I move around in Jantik Jog, the sky flashes back and forth between blue and white.

**Comment by Klikini** [comment]
Can anyone confirm that this is still an issue?

@Twinkletoe @sibilantsibyl @bribling

**Comment by RobertMcDermot** [comment]
I am not able to reproduce this issue and without a current response that says it's still happening, I'm going to close this bug. If it is still happening, feel free to open a new bug with details.
