### ISSUE TITLE
Chester Way 1A Teleporting

### ISSUE THREAD

**Issue by bellebellel** [ChildrenOfUr/coUclient#110]
On the little underground portion of this street if you get too close to the the wall on the right side you teleport up to the ground above it. I attached a picture that shows how close I can get to the wall before I teleport.
The picture of me above ground is where my character teleports to.
![screen shot 2014-08-16 at 7 06 50 am](https://cloud.githubusercontent.com/assets/8327341/3941586/7c50ca00-2535-11e4-85eb-d9d459dae0c9.png)

![screen shot 2014-08-16 at 7 05 40 am](https://cloud.githubusercontent.com/assets/8327341/3941583/523d6462-2535-11e4-9efa-bbb61a77f9f5.png)

**Comment by RobertMcDermot** [comment]
Walls are now paid attention to and you can no longer walk outside of the cave area you can see leading to the teleport problem described above (sorry about the 11 month wait).
