### ISSUE TITLE
Map Entity issues

### ISSUE THREAD

**Issue by ossans** [ChildrenOfUr/coUclient#124]
What it says on the tin! There's a floating shrine; I've attached an image for reference! 
![screenshot 2014-09-03 at 5 26 30 am](https://cloud.githubusercontent.com/assets/8641770/4133980/fee16572-3365-11e4-97b2-3c216fee7c18.png)

**Comment by RobertMcDermot** [comment]
I believe this issue to be fixed in the newest client as of today. Time will tell and I welcome more reports regarding this issue if they are found.

**Comment by ClearSkyPWB** [comment]
I have found floating things. In fact, I can't find the ground in Devi Drape!
![screen shot 2015-07-07 at 6 18 31 pm](https://cloud.githubusercontent.com/assets/13229969/8562128/ed2f4378-24f3-11e5-9837-e8e6940401b9.png)
