### ISSUE TITLE
Platforms in The Other Drop in Ilmenskie

### ISSUE THREAD

**Issue by Grackl** [ChildrenOfUr/coUclient#135]
The platforms don't work. It is like they aren't even there so you can't get to the top from below.

**Comment by RobertMcDermot** [comment]
I think this is more likely a bug with our street rendering (positioning/sizing). I explored a similar concern for Kaha Haha a little bit and the data seems like it should be correct but there are a select few streets such as both of The Drops and Kaha Haha where we are not accounting for something.

**Comment by Klikini** [comment]
Moved to https://github.com/ChildrenOfUr/cou-issues/issues/37
