### ISSUE TITLE
Selling Items

### ISSUE THREAD

**Issue by grax7** [ChildrenOfUr/coUclient#149]
I'm Using: Surface Pro 2 running Windows 8.1 and browser IE 11

Can only sell one item at a time. + and max buttons don't work, nor does typing in a different number, it always just sells one at a time.

**Comment by RobertMcDermot** [comment]
This is a decently old bug. As far as I know, selling items works as intended in the latest version of the game. If you are still having issues, please feel free to comment again or open a new bug report. Thanks for your help.
