### ISSUE TITLE
Quoins activate multiple times

### ISSUE THREAD

**Issue by scarahliz** [ChildrenOfUr/coUclient#171]
Certain Quoins will, once initially activated, disappear. However, if I walk back over the same spot (or even sometimes stand still), I will continue to get whatever reward the quoin gives (img, en, etc.). I tried leaving the street, and coming back to the same quoin -- it continued to give me multiples.

**Comment by Mixolyde** [comment]
It looks like the quoin continuously reappears under the player and keeps getting picked up. Maybe quoins shouldn't reappear if there is a player nearby. Can the server detect player positions?

**Comment by RobertMcDermot** [comment]
The mechanics behind quoin collection have changed significantly in recent weeks. The server now has much more control over quoin collection and this should mean that the above mentioned bug cannot occur. If you have any more trouble in the future or notice a different issue, please feel free to comment or open a new report.
