### ISSUE TITLE
Great Hole to lx

### ISSUE THREAD

**Issue by jellybino** [ChildrenOfUr/coUclient#173]
The hole to lx  (in Groddle Forest) doesn't go anywhere.  It's just a hole.  And there are some issues where you can see openings in the "dirt" and see background (sky and trees) within the holes.

**Comment by Klikini** [comment]
If you go all the way up and hit enter you'll be teleported. Though yes, it should be automatic.

**Comment by Klikini** [comment]
Added in commit https://github.com/ChildrenOfUr/coUclient/commit/628e498808ed054064b790637875f2137271870aa, will be included in the next release (aloeng with the other teleporters).
