### ISSUE TITLE
"Go To Tahli" graphics on Andra map are showing as white

### ISSUE THREAD

**Issue by Mixolyde** [ChildrenOfUr/coUclient#176]
When I click the map button in Andra, the "Go" image and the words "To Tahli" display incorrectly. Looks like the map image on the main Glitch site is missing it completely:

http://www.glitchthegame.com/locations/andra/

**Comment by Klikini** [comment]
![screenshot 2015-04-09 at 8 27 24 pm](https://cloud.githubusercontent.com/assets/1693960/7080389/de10d700-def6-11e4-9a0d-660bec112714.png)

**Comment by Klikini** [comment]
Fixed before fb1d239
