### ISSUE TITLE
Forum Signup Bug

### ISSUE THREAD

**Issue by Taliabear** [ChildrenOfUr/coUclient#181]
Tried signing in with Persona, and instead of what I assume is supposed to be a place to put in a username, what I get is some raw code below a Google search bar that looks like this:
null; var rsvdUsers = ["stootbarfield","hburger","kevbob","kukubee","muppethead","yetispaghetti"]; function updateButton() { inputValueFull = input.value.toLowerCase(); inputValue = inputValueFull.trim().replace(/ +(?= )/g,''); if (inputValueFull.length > 30 || inputValueFull.length < 3) { var dLength = true; $("#usernamehelp").show(); } else if (inputValueFull.length <= 30 && inputValueFull.length >= 3) { var dLength = false; $("#usernamehelp").hide(); } if ($.inArray(inputValue, usedUsers) > -1) { var dDup = true; $("#usernamedup").show(); } else { var dDup = false; $("#usernamedup").hide(); } if ($.inArray(inputValue, rsvdUsers) > -1) { var dDup = true; $("#usernameres").show(); } else { var dDup = false; $("#usernameres").hide(); } if (dLength == true || dDup == true) { $("#buttonUsername").addClass("disabled"); } else if (dLength == false || dDup == false) { $("#buttonUsername").removeClass("disabled"); } }

**Comment by RobertMcDermot** [comment]
Whoops. That was my bad. Was messing with some of the forum code and accidentally saved over the live version. Should be fixed now, back to the way it was.
