### ISSUE TITLE
Bugs and Fixes for the next Master Release

### ISSUE THREAD

**Issue by ppvk** [ChildrenOfUr/coUclient#193]
*Bugs*
- ~~Game Logout~~ - Paul
- ~~Create new user on forums~~ - Robert
- ~~Find out why 'Check your email' doesn't appear occasionally~~ - Paul
- ~~Password length, and proper email checking.~~ - Paul
- ~~Make loading music respect mute~~ - Robert
- ~~Context Menu placement~~ - Paul

---
edit as needed

**Comment by Klikini** [comment]
- Energy Limits (0 >= e >= max)
- Hide menu button, the menu is non-functional for now
- Calendar data OR disable calendar for now?

**Comment by RobertMcDermot** [comment]
I think it's fine to release something that doesn't work. If we waited until everything worked to give it to our users, we wouldn't have given them anything yet.
