### ISSUE TITLE
Can't get past login screen

### ISSUE THREAD

**Issue by nelsonam** [ChildrenOfUr/coUclient#200]
I made an account with my email, then it gives me the "what would you like to be called" dialog. I can't seem to get past this screen. I click the button but nothing happens. If I return to the site it seems to remember my choice of name, but then asks me for it again. Not sure what to do.

<img width="1915" alt="screen shot 2015-07-21 at 9 25 54 pm" src="https://cloud.githubusercontent.com/assets/557945/8817945/3bee01ba-2fef-11e5-9806-758f51cd81e7.png">

**Comment by RobertMcDermot** [comment]
@nelsonam Thank you for bringing this to my attention. I was making some changes to our auth server last night and made a bad push. I thought I had fixed it up but I see not completely. I have just pushed what I believe will fix your problem. Can you try logging in again and setting your username?

Let me know if you have any issues, but I'm hopeful that it will work this time.
