### ISSUE TITLE
Images of hatchet and hoe in inventory are missing the heads

### ISSUE THREAD

**Issue by montuos** [ChildrenOfUr/coUclient#201]
Images of hatchet and hoe in inventory are missing the heads.  They show up just fine in the street spirit.

![cou_headless_hoe](https://cloud.githubusercontent.com/assets/7076290/8841497/40a46c3a-30bc-11e5-82a4-7fef785133bc.png)
![cou_headless_hatchet](https://cloud.githubusercontent.com/assets/7076290/8841498/40a763d6-30bc-11e5-9920-0c5bb59c25f0.png)

**Comment by Klikini** [comment]
![image](https://cloud.githubusercontent.com/assets/1693960/8841964/005b42ea-30ba-11e5-95da-b630f710f8f4.png)

These (as well as many other items) have been fixed in the dev branch (going live soon)

**Comment by montuos** [comment]
Awesome!  Thank you!

**Comment by RobertMcDermot** [comment]
@Klikini I think those items might look better if you used the icon url in place of the sprite url. You can see the different style when looking at the pick in @montuos' inventory above. I personally like the icon url better which is why I used it for the pick (fills more of the frame).

**Comment by montuos** [comment]
RobertMcDermot makes a very good point about filling the frame; the smaller images are harder to distinguish one from the other.  This can be a major issue for people with less than perfect eyesight.  The images in the street spirit are easy to distinguish not just because of the larger size, but because of the differences in orientation as well.

**Comment by Klikini** [comment]
Better?

![image](https://cloud.githubusercontent.com/assets/1693960/8865590/ae67c93c-3176-11e5-927f-a9bf9c7d2fe7.png)

(I wanted to match that icon but wasn't sure how. `iconUrl -> spriteUrl`. Now I know :)

**Comment by montuos** [comment]
Great!  Now I can tell the difference even without my reading glasses!  :)
