### ISSUE TITLE
NPCs do not follow platform lines or obey walls

### ISSUE THREAD

**Issue by montuos** [ChildrenOfUr/coUclient#203]
Quality control issue:  On Doon Way in Groddle Forest, at the Berecroy Woods/Hayden Seek Alley end of the street, the area where you can travel doesn't extend as far as where the qurazy quoin is.  Attached screenshot shows where you stop moving forward, including any height of jumping.

![cou_qurazy_quoin_on_doon_way](https://cloud.githubusercontent.com/assets/7076290/9149314/e378a9be-3d71-11e5-8f49-3ece2934fec3.png)

**Comment by Klikini** [comment]
I moved it over to the left a bit (to the left of the spice plant)

**Comment by montuos** [comment]
You can now move to where the qurazy quoin used to be, except that a bottomless pit turned up there, like the one I reported for Stafli Joli.  Oops?

**Comment by Klikini** [comment]
Once you fall, can you get back up by walking left?

**Comment by montuos** [comment]
Um.  No idea?  I didn't get back in until now, and the barrier is back in front of the tree again.  So this is fixed as long as the street spirit can't get back there again (which I just realized appears between the trees in my screenshot up there).

**Comment by montuos** [comment]
...which it promptly did as soon as I turned my back to write that.  Do I assume correctly that fixing the floor against bottomless pits is harder than moving the vertical barriers?  Otherwise I guess we'll just have to accept that sometimes the street spirit is just going to be inaccessible behind those trees, and piggies too.
![cou_street_spirit_on_doon_way](https://cloud.githubusercontent.com/assets/7076290/9191907/7653b62a-3fd4-11e5-8428-11edf4d2a66f.png)
![cou_piggy_on_doon_way](https://cloud.githubusercontent.com/assets/7076290/9192066/81ca2da8-3fd5-11e5-8cbc-5ea1166ff154.png)

**Comment by RobertMcDermot** [comment]
In the future, npcs will be aware of floors/walls. Right now they have no idea about such things and simply wander back and forth.

**Comment by Klikini** [comment]
Moved to https://github.com/ChildrenOfUr/cou-issues/issues/36
