### ISSUE TITLE
Cannot sell gems to vendors

### ISSUE THREAD

**Issue by JulieJitzu** [ChildrenOfUr/coUclient#207]
Mining rocks and receiving gems. Attempting to sell to any local vendors results in currant amount adjusted in popup window, but then not reflected in overall currant amount. Gems then disappear from inventory as if having been sold. However, plain mined rocks are accepted and reflected in overall currant amount.

**Comment by Klikini** [comment]
Moved to https://github.com/ChildrenOfUr/cou-issues/issues/34
