### ISSUE TITLE
user "undefined"

### ISSUE THREAD

**Issue by celeloriel** [ChildrenOfUr/coUclient#213]
I'm using Chrome Version 49.0.2623.87 (64-bit)

After I log in, I am taken to the profile page: http://childrenofur.com/profile/?profileredirect=true&reason=undefined

And I'm shown this error message: "undefined could not be found."

I have no way to enter a username or change my username; clearly my login credentials work, but after the first time I logged in, where I saw the "select a username" screen for a moment before the page auto-reloaded with the error,  I haven't been able to get to that screen.  Please help.

**Comment by celeloriel** [comment]
Updating this: I was able to set a username (celeloriel), but my profile page is still uneditable.

**Comment by DTV96Calibre** [comment]
I experienced the same issue when I tried to create an account that I was going to grab my old profile with. The account I am currently able to use I made a while back. The email address I used and got the undefined error with I may have already tried using before in the past, have you already tried creating an account with that email before?

**Comment by Klikini** [comment]
This was caused by an HTTPS upgrade, which should be taken care of now.

If you're still having problems, open an issue at https://github.com/ChildrenOfUr/coUclient/issues :)
