### ISSUE TITLE
How do I build & run?

### ISSUE THREAD

**Issue by bfops** [ChildrenOfUr/coUclient#219]
Context: I'm new to Dart.

So far I've:
- Installed Dart + Dartium (not Dart Editor, because apparently active maintenance has stopped)
- Cloned the repo
- Installed deps with `pub get`
- Successfully run `dart build.dart` in the main folder
- Opened `web/index.html` in Dartium

But it gives me the "your browser might not support this" etc etc page. I assume I haven't built the client correctly.

Could somebody help me out? I notice the README says to open `web/game.html`, which doesn't exist for me - is that a stale README, or should the build be generating it?

Thanks!

**Comment by DTV96Calibre** [comment]
game.html is located at web/files/html
I was unable to successfully run dart build.dart; I get a bunch of polymer errors. Any suggestions?

**Comment by DTV96Calibre** [comment]
If the devs see this, we could really use an update on how new contributors can get set up. My friend and I would really love to contribute but it's difficult trying to get setup and we were interested in getting started months ago.

**Comment by ixaeon** [comment]
I briefly dabbled in this some time ago but haven't looked at it since
then. I'd also like to get some help or direction into getting back into
the project so I can try and fix some apparent bugs and help continue
adding features with the rest of the devs.

**Comment by lizzard** [comment]
Hey there. Here are my notes on how I build and run stuff. I'm not using Dartium though. I think one of the issues with running a local environment is that we are currently using Robert's api key and he may not want to hand that out to tons of people. I don't have a local copy of the db so I'm also pulling from his database for my local instance.  Anyway, here's my notes for what they're worth, mostly they are meant to get people started with github, but there is a bit on how to start the server and client going. 

[CoU-dev-env-setup.txt](https://github.com/ChildrenOfUr/coUclient/files/503920/CoU-dev-env-setup.txt)

**Comment by Mixolyde** [comment]
Thanks for this. I've taken a break from helping CoU to work on some other projects, but would love to get back into it some day.

**Comment by bfops** [comment]
I've also gotten caught up in other stuff in the meantime. I'd love to get back around to this and contribute, but it's hard to find the time!
