### ISSUE TITLE
GPS High CPU Usage

### ISSUE THREAD

**Issue by DTV96Calibre** [ChildrenOfUr/coUclient#221]
Using the navigation feature to get walking directions causes the game's performance to drop. If for whatever reason the navigation system can't find the location you're looking for, the performance drop is more severe. This can be reproduced by setting navigation to some street other than the one you're already at and comparing cpu usage to how it is with navigation turned off. For me usage nearly doubles for navigation that doesn't fail.

**Comment by Klikini** [comment]
Fixed
