### ISSUE TITLE
Game won't start since I teleported to Bortola Start

### ISSUE THREAD

**Issue by mariusmoo** [ChildrenOfUr/coUclient#222]
As an ex-greeter I wanted to see a start street again, so I teleported to Bortola Start. The game never loaded the street (it stayed on the loading screen). After reloading the page, I now can't load the game at all.

Browser: Chrome 56.0.2924.87 (64-bit)
OS: macOS Sierra 10.12.3 (16D32)

JS console contents:

`/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/index.html.polymer.bootstrap.dart.js:62533 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
prototypeForTag @ /index.html.polymer.bootstrap.dart.js:62533
polymer.min.js:14 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
shadowFromTemplate @ polymer.min.js:14
/index.html.polymer.bootstrap.dart.js:4583 Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
dart.aIz @ /index.html.polymer.bootstrap.dart.js:4583
/index.html.polymer.bootstrap.dart.js:42729 [SoundManager] Starting up... 0:00:00
/index.html.polymer.bootstrap.dart.js:42729 [Server Communication] Map data loaded. 0:00:00
/index.html.polymer.bootstrap.dart.js:42729 [SoundManager] Registered services 0:00:01
/index.html.polymer.bootstrap.dart.js:42729 [AuthManager] Setting API tokens 0:00:01
/index.html.polymer.bootstrap.dart.js:42729 [AuthManager] Logged in 0:00:02
/index.html.polymer.bootstrap.dart.js:42729 [StreetService] Requesting street "GA9S5T1LA0D27NG"... 0:00:02
/index.html.polymer.bootstrap.dart.js:42729 [StreetService] "GA9S5T1LA0D27NG" loaded. 0:00:02
/index.html.polymer.bootstrap.dart.js:42729 [StreetService] Assembling Street... 0:00:02
/index.html.polymer.bootstrap.dart.js:1315 Uncaught Error: NullError: method not found: 'h' on null
    at Object.J.m (/index.html.polymer.bootstrap.dart.js:56139)
    at Nh.<anonymous> (/index.html.polymer.bootstrap.dart.js:14609)
    at Nh.<anonymous> (/index.html.polymer.bootstrap.dart.js:14621)
    at /index.html.polymer.bootstrap.dart.js:14111
    at bdI.a (/index.html.polymer.bootstrap.dart.js:18278)
    at bdI.dart.bdI.$2 (/index.html.polymer.bootstrap.dart.js:18476)
    at bbS.dart.bbS.$1 (/index.html.polymer.bootstrap.dart.js:18470)
    at aFZ.dart.aFZ.i1 (/index.html.polymer.bootstrap.dart.js:21481)
    at eR.dart.eR.aSW.H.o.b.func [as aSW] (/index.html.polymer.bootstrap.dart.js:18973)
    at b9A.dart.b9A.$0 (/index.html.polymer.bootstrap.dart.js:19209)`

**Comment by Klikini** [comment]
This street is not in the game; the start street is Mira Mesh.

If you're still stuck, send me your game username and I can get you out.

Sorry I just now saw this, this repo isn't meant for issues. Instead, use https://github.com/ChildrenOfUr/coUclient/issues
