### ISSUE TITLE
Currant amounts sometimes don't change properly

### ISSUE THREAD

**Issue by Art10001** [ChildrenOfUr/coUclient#227]
They fluctuate a lot; sometimes you have the correct amount, sometimes you lose 1k (perhaps depending on on-hand balance) out of nowhere, and when you relog it returns, etc. The fake balance can prevent or allow you from buying stuff.

**Comment by Klikini** [comment]
You probably had two usernames by accident, one capitalized and one not. This should be prevented now, but if you're still having issues, open a ticket in the new repo: https://github.com/ChildrenOfUr/cou-issues/issues
