### ISSUE TITLE
Graphical error at high resolutions

### ISSUE THREAD

**Issue by saraphim78** [ChildrenOfUr/coUclient#53]
Sometimes they pop up, other times they won't.

**Comment by Klikini** [comment]
@saraphim78 Is this still an issue with the new UI?

**Comment by RobertMcDermot** [comment]
I do not believe this is still an issue. The current UI restricts the game size to a maximum (1300x750 currently). This is pictured below with a screen size of 3000x2000:
![current](https://cloud.githubusercontent.com/assets/5414318/7057389/23e861e6-de23-11e4-91b5-365195733822.png)
If I remove the max size restrictions, it game takes the whole screen, but you can see that if the level isn't big enough there can be some funniness:
![after](https://cloud.githubusercontent.com/assets/5414318/7057393/3f9d0ed2-de23-11e4-9880-199a90145d09.png)

Either way, I think the OP's problem should be solved unless we hear differently.
